"use client"

import * as React from 'react'

import './globals.css'
import type { Metadata } from 'next'
import NavBar from '@/components/navbar'

import { ChakraProvider, Container } from '@chakra-ui/react'
import theme from '@/components/theme'
import Fonts from '@/components/ui/fonts'
import Footer from '@/components/footer'


export const metadata: Metadata = {
  title: 'Homepage | HaiseErwin',
  description: 'Generated by koitran',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>
          <Fonts />
          <NavBar /> 
          <Container maxW="container.sm" pt={20} px={12}>
              {children}
          </Container>
          <Footer />
        </ChakraProvider>
        </body>
    </html>
  )
}
